name: ✨ Feature request
description: Suggest functionality that could be added to the provider
title: "✨ <title>"
assignees:
  - dglsparsons
body:
  - type: textarea
    attributes:
      label: What functionality would you like to see?
      description: A short description of what you'd like to see added. If this relates to existing resources or data sources, please include that information.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example
      description: If you have an example of what this could look like, please include it here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Details
      description: Please add any other context.
    validations:
      required: false
